### PR TITLE
Switch to native asserts

### PR DESCRIPTION
**Pull request by davehunt**
@stephendonner r?

### CODE REVIEW

**Comment by davehunt** [comment]
It looks like dev has some unrelated issues, but here's a passing adhoc run for staging: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/mozillians.adhoc/47/

**Comment by johngian** [comment]
@davehunt tests are failing on dev because of a known regression. We already have a PR that (most probably) fixes it.

**Comment by davehunt** [comment]
Thanks @johngian! You're welcome to review this patch if you have time. We have removed the use of unittestzero from all of our suites as it's an unnecessary dependency given pytest's awesome handling of native assertions.

**Comment by rbillings** [comment]
The changes look good visually, leaving this open for someone else to check on dev. R+

**Pull request merged**
