### PR TITLE
Fix group creation test for the new modal

### PR DESCRIPTION
**Pull request by comzeradd**
This fixes the `test_that_user_can_create_and_delete_group` that currently fails due to UI changes on groups

### CODE REVIEW

**Comment by comzeradd** [comment]
@davehunt r?

**Comment by stephendonner** [comment]
This LGTM, but can you please rebase, @comzeradd ?  Thanks!  r+

**Comment by comzeradd** [comment]
@stephendonner PR rebased

**Comment by davehunt** [comment]
r+ here too, note that mozillians.stage will fail due to element not found until staging is updated. If this is undesirable, please add an xfail to affected tests.

**Pull request merged**
