### PR TITLE
Add shields

### PR DESCRIPTION
**Pull request by stephendonner**
I'd prefer to address splitting the License into its own file (as seems precedent in https://github.com/mozilla/Addon-Tests/blob/4fcb07152f80285c57ff86014b9042bb61b0d3ee/LICENSE) in a separate pull, but can be cajoled into doing so here (scope creep a bit, though).

### CODE REVIEW

**Comment by stephendonner** [comment]
See it in action here: https://github.com/stephendonner/mozillians-tests/tree/add-shields

**Comment by m8ttyB** [comment]
r+

**Comment by stephendonner** [comment]
Thx; merging in

**Pull request merged**
