### PR TITLE
Click recaptcha box on user registration.

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by johngian** [comment]
This should be fixing this issue:
```
Failed 	tests/test_register.py::TestRegister::()::test_profile_creation
```

**Comment by johngian** [comment]
@stephendonner r?

**Comment by stephendonner** [comment]
Ran this through Sauce Labs, and it's failing on the recaptcha click:

https://pastebin.mozilla.org/8912228

**Comment by johngian** [comment]
From IRC:

```
Project mozillians.stage build #1359: FIXED
Project mozillians.stage.saucelabs build #1387: FIXED
```

and

``
 37 passed, 0 skipped, 0 failed, 0 errors, 1 expected failures, 0 unexpected passes 
``

I think we are good.

@akatsoulas r?

**Comment by akatsoulas** [comment]
python code looks good. r+

**Pull request merged**
