### PR TITLE
xfail failing test

### PR DESCRIPTION
**Pull request by m8ttyB**

### CODE REVIEW

**Comment by m8ttyB** [comment]
This is a simple xfail and low risk. Merging.

**Comment by comzeradd** [comment]
I think you marked the wrong test.

**Comment by stephendonner** [comment]
Indeed; this xfailed test_group_deletion_confirmation, but looks like it should've xfailed test_group_invitations:

17:02:39 FAIL ../tests/test_group.py::TestGroup::()::test_group_invitations
17:02:39 XFAIL ../tests/test_group.py::TestGroup::()::test_group_deletion_confirmation
17:02:39   https://github.com/mozilla/mozillians-tests/issues/231

Can you please revert and re-issue a pull to xfail the right test?

**Comment by m8ttyB** [comment]
@stephendonner yep. It's done, check #233

**Pull request merged**
